apiVersion: apps/v1
kind: Deployment
metadata:
 name: myapp-dpl
 namespace: sentence-ai
 labels:
   app: myapp-dpl
spec:
 replicas: 1
 selector:
   matchLabels:
     app: myapp-dpl
 template:
   metadata:
     labels:
       app: myapp-dpl
   spec:
     containers:
     - name: myapp-container
       image: lumix026/sentence-ai:latest
       ports:
       - containerPort: 5000
     volumes:
      - name: myapp
        persistentVolumeClaim:
          claimName: sentence-ai-pvc