apiVersion: apps/v1
kind: Deployment
metadata:
 name: ollama-dpl
 namespace: sentence-ai
 labels:
   app: ollama-dpl
spec:
 replicas: 1
 selector:
   matchLabels:
     app: ollama-dpl
 template:
   metadata:
     labels:
       app: ollama-dpl
   spec:
     containers:
     - name: ollama-container
       image: ollama/ollama
       ports:
       - containerPort: 11434
       volumeMounts:
       - mountPath: /root/.ollama
         name: ollama
         subPath: ollama
     volumes:
      - name: ollama
        persistentVolumeClaim:
          claimName: sentence-ai-pvc