apiVersion: v1
kind: Service
metadata:
  name: myapp-svc
  namespace: sentence-ai
spec:
  selector:
    app: myapp-dpl
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 12000
      targetPort: 5000