apiVersion: v1
kind: Service
metadata:
  name: ollama-svc
  namespace: sentence-ai
spec:
  selector:
    app: ollama-dpl
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 11434
      targetPort: 11434