apiVersion: v1
kind: Service
metadata:
  name: webui-svc
  namespace: sentence-ai
spec:
  selector:
    app: webui-dpl
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 8080
      