apiVersion: v1
kind: PersistentVolume
metadata:
  name: sentence-ai-pv
  labels:
    app: sentence-ai-pv
spec:
  storageClassName: default
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/snap/microk8s/common/default-storage/sentence-ai
    type: DirectoryOrCreate